# Numpy Array Properties & Attributes


## 1)Shape

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
arr1.shape

(5,)

In [6]:
arr2 = np.array([[1,2,3,4],[5,6]])
arr2.shape

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [9]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3.shape

(2, 3)

###### Shape attribute is basically use for to find number Rows,column and number of matrix but the number of rows and columns must be same otherwise it will give an error as given on arr2

In [11]:
arr4 = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]] ,dtype = np.int8)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
arr4.shape

(2, 2, 2)

## 2) ndim is used for to find the dimensions of the given array

In [17]:
arr4.ndim

3

In [18]:
arr3.ndim

2

## 3) Next is Size and Itemsize size is used for that how many items are there in the given array 
## 4) while In NumPy, itemsize refers to the size in bytes of a single element within a NumPy array. It indicates the memory occupied by each individual item, not the total number of items or the array's dimensions

In [28]:
arr1.size

5

##### there are 5 iteams in arr1

In [30]:
arr4.itemsize

8

## 5) Dtype is used for to describes the following aspects of the data: Type of the data (integer, float, Python object, etc.)

In [33]:
arr1.dtype

dtype('int64')

##### int is datatype and 64 is memory occoupied space we can change it manually means we can convert from bit to bytes

In [34]:
arr5 = np.array([1,2,3] , dtype = np.int8)
arr5.itemsize

1

## 6) astype is used for the conversion of the datatpye of a give array

In [40]:
arr6 = np.array([1,34,56,23])
arr6

array([ 1, 34, 56, 23])

In [41]:
arr6.astype('float')

array([ 1., 34., 56., 23.])